{% set name = "file-tree-fsl" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/file-tree-fsl-{{ version }}.tar.gz
  sha256: 744d39f597b74ea7c78246f3a849c82cf1e1fe2cfe765f21da58f6aa18008f6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - file-tree
    - python >=3.6

test:
  imports:
    - file_tree_fsl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.fmrib.ox.ac.uk/ndcn0236/file-tree-fsl
  summary: Filetree definitions for the FSL neuroimaging library
  license: MIT
  license_file: LICENSE
  doc_url: https://open.win.ox.ac.uk/pages/ndcn0236/file-tree

extra:
  recipe-maintainers:
    - MichielCottaar
